# Generated by Django 5.2.3 on 2025-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='emp_photo')),
            ],
        ),
    ]
